### ISSUE TITLE
A little bug in unit toolkit (Tutorial 03)

### ISSUE THREAD

**Issue by Yu-Tang-Lin** [openforcefield/openff-evaluator#415] opened 2022-01-24 23:23 UTC
In the "Plotting the Results" part:

Original:
[7] 
from openff.units import unit

It should be:
[7]
from openff.evaluator import unit

I guess there is an update in "unit". Same question as Tutorial 01

**Comment by mattwthompson** [comment] 2022-11-16 16:25
Duplicate of #414

**Closed by mattwthompson** 2022-11-16 16:25 UTC
